backend/accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.UserSignUp.as_view(), name='signup'),
    path('signup/done', TemplateView.as_view(template_name="accounts/signup_done.html"), name="signup_done"),
    path('activate/<str:uidb64>/<str:token>', views.UserActivation.as_view(), name='activate'),
    path('profile/', views.UserProfile.as_view(), name='profile'),
    # path('guide/', TemplateView.as_view(template_name="accounts/guide_book.html"), name="guide"),
    path('pack/', views.UserPack.as_view(), name='pack')
]

backend/backend/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.staticfiles.views import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(template_name='index.html', extra_context={
        "ignore_header": True
    }, redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('accounts/', include('accounts.urls')),  # for user signup
    path('cobra/', include('cobra_wrapper.urls')),
    path('database/', include('bigg_database.urls')),
    path('data/', include('data_wrapper.urls')),
    path('share/', include('share.urls')),
    path('favicon.ico', serve, {'path': 'icon/favicon.ico'}),
]

backend/share/urls.py
from django.urls import path

from . import views

app_name = 'share'
urlpatterns = [
    path('create/', views.CreateShareLinkView.as_view(), name='create_share'),
    path('model/<int:pk>', views.ModelShareView.as_view(), name='shared_cobra_model'),
    path('addToModel/', views.AddToMyModel.as_view(), name='add_to_model')
    # path('reaction/<int:pk>', views.ReactionShareView.as_view(), name='shared_cobra_reaction'),
    # path('metabolite/<int:pk>', views.MetaboliteShareView.as_view(), name='shared_cobra_metabolite'),
]

backend/accounts/models.py
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models

from bigg_database.models import Model, Metabolite, Gene, Reaction
from cobra_wrapper.models import CobraModel as ComputationalModel
from biobricks.models import Biobrick


class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    target_content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    target_object_id = models.PositiveIntegerField()
    target = GenericForeignKey('target_content_type', 'target_object_id')

backend/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserSignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

backend/accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View, CreateView
from .forms import UserSignUpForm
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from .models import Favorite
from django.apps import apps
from django.core.paginator import Paginator


class UserSignUp(CreateView):
    template_name = 'accounts/signup.html'
    form_class = UserSignUpForm
    # success_url = reverse_lazy('login')  # this router is loaded after accounts app, so use reverse_lazy

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save()
            user.is_active = False
            user.save()

            mail_subject = 'Activate your account'
            current_site = get_current_site(request)
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            token = account_activation_token.make_token(user)
            to_email = form.cleaned_data.get('email')
            message = render_to_string('accounts/activate_email.html', {
                "protocol": "http",  # FIXME: protocol
                "domain": current_site,
                "uid": uid,
                "token": token,
                "email": to_email,
            })
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return redirect("accounts:signup_done")
        else:
            return render(request, "accounts/signup.html", {
                "form": form,
            })


class UserActivation(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            # login(request, user)
            success = True
        else:
            success = False

        return render(request, "accounts/activate_done.html", {
            "success": success
        })


class UserProfile(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        return render(request, "accounts/profile.html", {
            "first": user.first_name,
            "last": user.last_name,
            "username": user.username,
        })

    def post(self, request):
        first = request.POST.get("first")
        last = request.POST.get("last")
        user = request.user

        if first and last:
            user.first_name = first
            user.last_name = last
            user.save()

        return redirect("accounts:profile")


@method_decorator(csrf_exempt, name='dispatch')  # temporary workaround
class UserPack(LoginRequiredMixin, View):
    def get(self, request):
        obj_type = request.GET.get("type")
        page = request.GET.get("page", 1)

        counts = {
            "model": Favorite.objects.filter(user=request.user, target_content_type=ContentType.objects.get(
                app_label='bigg_database', model='model')).count(),
            "usermodel": Favorite.objects.filter(user=request.user, target_content_type=ContentType.objects.get(
                app_label='share', model='sharemodel')).count(),
            "reaction": Favorite.objects.filter(user=request.user, target_content_type=ContentType.objects.get(
                app_label='bigg_database', model='reaction')).count(),
            "gene": Favorite.objects.filter(user=request.user, target_content_type=ContentType.objects.get(
                app_label='bigg_database', model='gene')).count(),
            "metabolite": Favorite.objects.filter(user=request.user, target_content_type=ContentType.objects.get(
                app_label='bigg_database', model='metabolite')).count()
        }

        if not obj_type:
            obj_type = "model"

        queryset = None
        if obj_type == "model":
            queryset = Favorite.objects.filter(user=request.user, target_content_type=ContentType.objects.get(
                app_label='bigg_database', model='model'))
        elif obj_type == "usermodel":
            queryset = Favorite.objects.filter(user=request.user, target_content_type=ContentType.objects.get(
                app_label='share', model='sharemodel'))
        elif obj_type == "reaction":
            queryset = Favorite.objects.filter(user=request.user, target_content_type=ContentType.objects.get(
                app_label='bigg_database', model='reaction'))
        elif obj_type == "gene":
            queryset = Favorite.objects.filter(user=request.user, target_content_type=ContentType.objects.get(
                app_label='bigg_database', model='gene'))
        elif obj_type == "metabolite":
            queryset = Favorite.objects.filter(user=request.user, target_content_type=ContentType.objects.get(
                app_label='bigg_database', model='metabolite'))

        paginator = Paginator(queryset, 10)
        items = paginator.get_page(page)

        return render(request, "accounts/pack.html", {
            "type": obj_type,
            "counts": counts,
            "this_cnt": queryset.count(),
            "page_obj": items,
            "paginator": paginator,
            "is_paginated": False if queryset.count() <= 10 else True
        })

    # this favorite implementation uses django-favorite
    def post(self, request):
        user = request.user
        target_model = apps.get_model(app_label=request.POST['target_app'],
                                      model_name=request.POST['target_name'])
        target_content_type = ContentType.objects.get_for_model(target_model)
        target_object_id = request.POST['target_object_id']

        # delete it if it's already a favorite
        if user.favorite_set.filter(target_content_type=target_content_type,
                                    target_object_id=target_object_id):
            user.favorite_set.get(target_content_type=target_content_type,
                                  target_object_id=target_object_id).delete()
            status = 'deleted'

        # otherwise, create it
        else:
            user.favorite_set.create(target_content_type=target_content_type,
                                     target_object_id=target_object_id)
            status = 'added'

        response = {'status': status,
                    'fav_count': Favorite.objects.filter(target_content_type=target_content_type,
                                                         target_object_id=target_object_id).count()}

        return JsonResponse(response)

backend/accounts/templates/accounts/activate_done.html
{% extends "base.html" %}

{% block title %}
Account activation successful
{% endblock %}

{% block content %}
    <div class="container mt-4">
        {% if success %}
            <p>Now you can login your account.</p>
        {% else %}
            <p>This activation link is invalid.</p>
        {% endif %}
    </div>
{% endblock %}

backend/accounts/templates/accounts/activate_email.html
You received this email because someone registered an account for email {{ email }} on our website.

If you want to activate your account, follow the link below:
{{ protocol }}://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

Otherwise, you can ignore this email.

backend/accounts/templates/accounts/guide_book.html
{% extends "base.html" %}
{# TODO: a better place for this template #}
{% block title %}
Guide Book
{% endblock %}

{% block content %}
    <div class="banner w-100">
    <div class="container d-flex align-items-center">
      <div class="icon bg-info text-white d-flex justify-content-center align-items-center">
        <i class="fa fa-book fa-2x"></i>
      </div>
      <div class="des ml-3">
        <h5>Guide Book</h5>
        <div>How to use Foresyn?</div>
      </div>
    </div>
  </div>
  <div id="guide-book" class="container" style="padding: 0px"><br>
    <h3>Guide Book</h3>
    <br>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
  </div>
{% endblock %}

backend/accounts/templates/accounts/pack.html
{% extends "base.html" %}
{% load favorite_list_tag %}
{% load static %}
{% load calc_index_display_tag %}
{% block title %}
    My Pack
{% endblock %}

{% block content %}
    <div class="banner w-100">
        <div class="container d-flex align-items-center">
            <div class="icon bg-info text-white d-flex justify-content-center align-items-center">
                <i class="fa fa-star fa-2x"></i>
            </div>
            <div class="des ml-3">
                <h5>My Pack</h5>
                <div>Here contains things you like.</div>
            </div>
        </div>
    </div>
    <div class="container mt-4">
        <div class="row">
            <div class="left_index col-3">
                <ul class="list-group text-primary">
                    <a {% if counts.gene != 0 %} href="?type=gene" {% else %} href="#" {% endif %}
                                                 class="list-group-item {% if type == "gene" %} chosen {% endif %} {% if counts.gene == 0 %} disabled {% endif %}">Gene<span
                            class="badge badge-info badge-search">{{ counts.gene }}</span></a>
                    <a {% if counts.reaction != 0 %} href="?type=reaction" {% else %} href="#" {% endif %}
                                                     class="list-group-item {% if type == "reaction" %} chosen {% endif %} {% if counts.reaction == 0 %} disabled {% endif %}">Reaction<span
                            class="badge badge-info badge-search">{{ counts.reaction }}</span></a>
                    <a {% if counts.metabolite != 0 %} href="?type=metabolite" {% else %} href="#" {% endif %}
                                                       class="list-group-item {% if type == "metabolite" %} chosen {% endif %} {% if counts.metabolite == 0 %} disabled {% endif %}">Metabolite<span
                            class="badge badge-info badge-search">{{ counts.metabolite }}</span></a>
                    <a {% if counts.model != 0 %} href="?type=model" {% else %} href="#" {% endif %}
                                                  class="list-group-item {% if type == "model" %} chosen {% endif %} {% if counts.model == 0 %} disabled {% endif %}">Model (Database)<span
                            class="badge badge-info badge-search">{{ counts.model }}</span></a>
                    <a {% if counts.model != 0 %} href="?type=usermodel" {% else %} href="#" {% endif %}
                                                  class="list-group-item {% if type == "usermodel" %} chosen {% endif %} {% if counts.usermodel == 0 %} disabled {% endif %}">Model (User)<span
                            class="badge badge-info badge-search">{{ counts.usermodel }}</span></a>
                </ul>
            </div>
            <div class="right_content col-9">

                <h5 class="result_num">{{ this_cnt }} results</h5>
                <div class="list-group list-group-flush mb-5">
                    {% for item in page_obj %}
                        <div href="#" class="list-group-item">
                            <div class="d-flex w-100 justify-content-between">
                                <a class="mb-1" href="{% render_link_tag item %}"><h5>{{ item|get_object_name }}</h5></a>
                                {% pack_favorite_button item %}
                            </div>
                            <p class="mb-1">{{ item|get_object_description }}</p>
                            <small>{{ item|get_object_source }}</small>
                        </div>
                    {% endfor %}
                </div>
                  {% if is_paginated %}
                  {% calc_index_display_tag %}
                  {% endif %}
            </div>
        </div>
    </div>

    <script src="{% static "javascript/favorite_button.js" %}"></script>
{% endblock %}

backend/accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Profile
{% endblock %}

{% block content %}
    <div class="banner w-100">
        <div class="container d-flex align-items-center">
            <div class="icon bg-info text-white d-flex justify-content-center align-items-center">
                <i class="fa fa-user fa-2x"></i>
            </div>
            <div class="des ml-3">
                <h5>My Profile</h5>
                <div>Here contains your information.</div>
            </div>
        </div>
    </div>
    <div class="container">
        <!-- Tab panes -->
        <div class="tab-content">
            <div id="my-profile" class="container tab-pane fade show active" style="padding: 0px"><br>
                <div class="card">
                    <div class="card-body">
                        <form class="row" action="." method="POST">
                            {% csrf_token %}
                            <div class="col-3">
                                <img class="rounded" src="{% static "image/avatar.jpg" %}"
                                     style="height:250px;border:3px solid #EEEEEE">
                            </div>
                            <div class="col-9">
                                <div class="col-12">
                                    <div class="row mt-4">
                                        <label for="validationDefault01" class="col-sm-2 col-form-label text-center">First
                                            name</label>
                                        <div class="col-sm-10">
                                            <input type="text" class="form-control" id="validationDefault01"
                                                   placeholder="First name"
                                                   value="{{ first }}" name="first">
                                        </div>
                                    </div>
                                    <div class="row mt-4">
                                        <label for="validationDefault02" class="col-sm-2 col-form-label text-center">Last
                                            name</label>
                                        <div class="col-sm-10">
                                            <input type="text" class="form-control" id="validationDefault02"
                                                   placeholder="Last name"
                                                   value="{{ last }}" name="last">
                                        </div>
                                    </div>
                                    <div class="row mt-4">
                                        <label for="validationDefaultUsername"
                                               class="col-sm-2 col-form-label text-center">Username</label>
                                        <div class="col-sm-10">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text" id="inputGroupPrepend2">@</span>
                                                </div>
                                                <input type="text" disabled class="form-control"
                                                       id="validationDefaultUsername"
                                                       placeholder="Username" aria-describedby="inputGroupPrepend2"
                                                       required value="{{ username }}">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row mt-4">
                                        <div class="col justify-content-around d-flex">
                                            <button class="col-4 btn btn-outline-light btn-side-circle text-hover-green"
                                                    type="submit">Save
                                            </button>
                                            <a class="col-4 btn btn-outline-light btn-side-circle text-hover-green"
                                               href="{% url 'password_change' %}">Change Password
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

backend/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
Sign up
{% endblock %}

{% block content %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

    <div class="container mt-4">
<form method="post" action="{% url 'accounts:signup' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
    </div>
{% endblock %}

backend/accounts/templates/accounts/signup_done.html
{% extends "base.html" %}

{% block title %}
Signup confirm email sent
{% endblock %}

{% block content %}
    <div class="container mt-4">
    <p>We've emailed you instructions for activating your account. If they haven't arrived in a few minutes, check your spam folder.</p>
    </div>
{% endblock %}