backend/backend/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.staticfiles.views import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(template_name='index.html', extra_context={
        "ignore_header": True
    }, redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('accounts/', include('accounts.urls')),  # for user signup
    path('cobra/', include('cobra_wrapper.urls')),
    path('database/', include('bigg_database.urls')),
    path('data/', include('data_wrapper.urls')),
    path('share/', include('share.urls')),
    path('favicon.ico', serve, {'path': 'icon/favicon.ico'}),
]

backend/cobra_wrapper/urls.py
from django.urls import path

from . import views, api_views

app_name = 'cobra_wrapper'
urlpatterns = [
    path('models/', views.CobraModelListView.as_view(), name='cobramodel_list'),
    path('models/<int:pk>/', views.CobraModelDetailView.as_view(), name='cobramodel_detail'),
    path('models/<int:pk>/map/', views.CobraModelMapView.as_view(), name='cobramodel_map'),
    path('models/<int:pk>/json/', api_views.CobraModelDetailJsonView.as_view(), name='cobramodel_detail_json'),
    path('models/create/', views.CobraModelCreateView.as_view(), name='cobramodel_create_form'),
    path('models/<int:pk>/delete/', views.CobraModelDeleteView.as_view(), name='cobramodel_confirm_delete'),
    path('models/<int:pk>/update/', views.CobraModelUpdateView.as_view(), name='cobramodel_update_form'),
    path('models/<int:pk>/change/<int:change_pk>/restore/', views.CobraModelChangeRestoreView.as_view(),
         name='cobramodel_change_restore'),

    path('models/<int:model_pk>/fba/', views.CobraFbaListView.as_view(), name='cobrafba_list'),
    path('models/<int:model_pk>/fba/<int:pk>/', views.CobraFbaDetailView.as_view(), name='cobrafba_detail'),
    path('models/<int:model_pk>/fba/<int:pk>/json/', api_views.CobraFbaDetailJsonView.as_view(),
         name='cobrafba_detail_json'),
    path('models/<int:model_pk>/fba/create/', views.CobraFbaCreateView.as_view(), name='cobrafba_create_form'),
    path('models/<int:model_pk>/fba/<int:pk>/delete/', views.CobraFbaDeleteView.as_view(),
         name='cobrafba_confirm_delete'),

    path('models/<int:model_pk>/rgefba/', views.CobraRgeFbaListView.as_view(), name='cobrargefba_list'),
    path('models/<int:model_pk>/rgefba/<int:pk>/', views.CobraRgeFbaDetailView.as_view(), name='cobrargefba_detail'),
    path('models/<int:model_pk>/rgefba/<int:pk>/json/', api_views.CobraRgeFbaDetailJsonView.as_view(),
         name='cobrargefba_detail_json'),
    path('models/<int:model_pk>/rgefba/create/', views.CobraRgeFbaCreateView.as_view(), name='cobrargefba_create_form'),
    path('models/<int:model_pk>/rgefba/<int:pk>/delete/', views.CobraRgeFbaDeleteView.as_view(),
         name='cobrargefba_confirm_delete'),

    path('models/<int:model_pk>/fva/', views.CobraFvaListView.as_view(), name='cobrafva_list'),
    path('models/<int:model_pk>/fva/<int:pk>/', views.CobraFvaDetailView.as_view(), name='cobrafva_detail'),
    path('models/<int:model_pk>/fva/<int:pk>/json', api_views.CobraFvaDetailJsonView.as_view(),
         name='cobrafva_detail_json'),
    path('models/<int:model_pk>/fva/create/', views.CobraFvaCreateView.as_view(), name='cobrafva_create_form'),
    path('models/<int:model_pk>/fva/<int:pk>/delete/', views.CobraFvaDeleteView.as_view(),
         name='cobrafva_confirm_delete'),
]

backend/share/urls.py
from django.urls import path

from . import views

app_name = 'share'
urlpatterns = [
    path('create/', views.CreateShareLinkView.as_view(), name='create_share'),
    path('model/<int:pk>', views.ModelShareView.as_view(), name='shared_cobra_model'),
    path('addToModel/', views.AddToMyModel.as_view(), name='add_to_model')
    # path('reaction/<int:pk>', views.ReactionShareView.as_view(), name='shared_cobra_reaction'),
    # path('metabolite/<int:pk>', views.MetaboliteShareView.as_view(), name='shared_cobra_metabolite'),
]

backend/cobra_wrapper/views.py
import json

from django.shortcuts import get_object_or_404, reverse, Http404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, TemplateView, FormView, View
from django.views.generic.edit import DeletionMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import Form
from django.utils import timezone

from . import models, forms
from .utils import load_comma_separated_str

from backend.celery import app
from search.internal_api import search_biobricks


class CobraModelListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        return models.CobraModel.objects.filter(owner=self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(object_list=object_list, **kwargs)
        context_data['form'] = forms.CobraModelCreateForm()
        return context_data


class CobraModelDetailView(LoginRequiredMixin, DetailView):
    def get_object(self, queryset=None):
        return get_object_or_404(models.CobraModel, owner=self.request.user, pk=self.kwargs['pk'])

    def get_update_forms(self):
        return [form() for form in forms.cobra_model_update_forms.values()]

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data()
        context_data['forms'] = self.get_update_forms()
        context_data['reactions'] = json.loads(self.object.reactions)
        context_data['metabolites'] = json.loads(self.object.metabolites)
        context_data['genes'] = json.loads(self.object.genes)
        context_data['latest_changes'] = models.CobraModelChange.objects.filter(model=self.object)[:10]
        context_data['change_line_len'] = context_data['latest_changes'].count() * 95

        keywords = set()
        reaction_dict_list = [
            json.loads(change.reaction_info)
            for change in models.CobraModelChange.objects.filter(
                model=self.object, change_type__in=['add_reaction', 'del_reaction'])[:10]
        ]
        for reaction_dict in reaction_dict_list:
            for reaction in reaction_dict['reactions']:
                keywords.add(reaction['name'])
                keywords.update(reaction['metabolites'])
                keywords.update(reaction['genes'])
        context_data['biobricks'] = search_biobricks(*keywords)

        return context_data


class CobraModelMapView(LoginRequiredMixin, TemplateView):
    template_name = 'cobra_wrapper/cobramodel_map.html'


class CobraModelCreateView(LoginRequiredMixin, FormView):
    http_method_names = ['post']
    template_name = 'cobra_wrapper/cobramodel_list.html'
    form_class = forms.CobraModelCreateForm

    def form_valid(self, form: forms.CobraModelCreateForm):
        self.new_model = form.save(self.request.user)
        return super().form_valid(form)

    def get_success_url(self):
        return self.new_model.get_absolute_url()


class CobraModelDeleteView(LoginRequiredMixin, DeletionMixin, View):
    http_method_names = ['post']
    success_url = reverse_lazy('cobra_wrapper:cobramodel_list')

    def get_object(self):
        return get_object_or_404(models.CobraModel, owner=self.request.user, pk=self.kwargs['pk'])


class CobraModelUpdateView(LoginRequiredMixin, FormView):
    http_method_names = ['post']
    template_name_suffix = '_update_form'

    def get_object(self):
        return get_object_or_404(models.CobraModel, owner=self.request.user, pk=self.kwargs['pk'])

    def get_forms(self):
        return [form() for form in forms.cobra_model_update_forms.values()]

    def get_form_class(self):
        change_type = self.request.POST.get('change_type', None)
        try:
            return forms.cobra_model_update_forms[change_type]
        except KeyError:
            if self.request.method == 'GET':
                return None
            else:
                raise Http404()

    def get_form(self, form_class=None):
        self.form_class = self.get_form_class()
        if self.form_class is None:
            return None
        else:
            form = super().get_form()
            self.object = self.get_object()
            form.model_object = self.object
            return form

    def form_valid(self, form):
        form.save(self.object)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('cobra_wrapper:cobramodel_detail', kwargs={'pk': self.object.pk})


# class CobraModelChangeRestoreView(FormView):
#     http_method_names = ['post']
#     form_class = forms.CobraModelChangeRestoreForm
#
#     def get_object(self):
#         model_object = get_object_or_404(models.CobraModel, pk=self.kwargs['pk'], owner=self.request.user)
#         return get_object_or_404(models.CobraModelChange, pk=self.kwargs['change_pk'], model=model_object)
#
#     def form_valid(self, form: forms.CobraModelChangeRestoreForm):
#         change = self.get_object()
#         self.new_model = change.restore(name=form.cleaned_data['name'], desc=form.cleaned_data['desc'])
#
#     def get_success_url(self):
#         return reverse(self.new_model)


class CobraModelChangeRestoreView(View):
    http_method_names = ['post']

    def get_object(self):
        model_object = get_object_or_404(models.CobraModel, pk=self.kwargs['pk'], owner=self.request.user)
        return get_object_or_404(models.CobraModelChange, pk=self.kwargs['change_pk'], model=model_object)

    def post(self, request, *args, **kwargs):
        change = self.get_object()
        new_model = change.restore('Restored from {}'.format(change.model.name),
                                   timezone.now().strftime('%Y-%m-%d %H:%M:%S'))
        return redirect(new_model)


class TemplateAddModelPkMixin:
    def get_context_data(self: TemplateView, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_pk'] = self.kwargs['model_pk']
        return context


class InsertModelForFormMixin:
    def get_form(self: FormView, form_class=None):
        self.model_object = get_object_or_404(models.CobraModel, pk=self.kwargs['model_pk'], owner=self.request.user)
        form = super().get_form()
        form.model_object = self.model_object
        return form


class CobraFbaListView(LoginRequiredMixin, TemplateAddModelPkMixin, ListView):
    def get_queryset(self):
        model = get_object_or_404(models.CobraModel, pk=self.kwargs['model_pk'], owner=self.request.user)
        return model.fba_list.all()

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['form'] = forms.CobraFbaForm()
        return context_data


class CobraFbaDetailView(LoginRequiredMixin, TemplateAddModelPkMixin, DetailView):
    def get_object(self, queryset=None):
        self.model_object = get_object_or_404(models.CobraModel, pk=self.kwargs['model_pk'], owner=self.request.user)
        return get_object_or_404(self.model_object.fba_list.all(), pk=self.kwargs['pk'])


class CobraFbaCreateView(LoginRequiredMixin, InsertModelForFormMixin, TemplateAddModelPkMixin, CreateView):
    http_method_names = ['post']
    template_name = 'cobra_wrapper/cobrafba_list.html'
    model = models.CobraFba
    form_class = forms.CobraFbaForm

    def form_valid(self, form: Form):
        form.instance.model = self.model_object
        response = super().form_valid(form)
        result = app.send_task(
            'cobra_computation.tasks.cobra_fba',
            kwargs={
                'pk': self.object.pk,
                'model_sbml': self.model_object.sbml_content,
                'deleted_genes': load_comma_separated_str(form.cleaned_data['deleted_genes']),
                'computation_type': 'normal',
            },
            queue='cobra_feeds',
            routing_key='cobra_feed.fba',
        )
        self.object.task_id = result.id
        self.object.save()
        return response

    def get_success_url(self):
        return reverse('cobra_wrapper:cobrafba_list', kwargs={'model_pk': self.kwargs['model_pk']})


class CobraFbaDeleteView(LoginRequiredMixin, DeletionMixin, View):
    http_method_names = ['post']

    def get_object(self):
        model = get_object_or_404(models.CobraModel, pk=self.kwargs['model_pk'], owner=self.request.user)
        return get_object_or_404(model.fba_list.all(), pk=self.kwargs['pk'])

    def get_success_url(self):
        return reverse('cobra_wrapper:cobrafba_list', kwargs={'model_pk': self.kwargs['model_pk']})


class CobraRgeFbaListView(LoginRequiredMixin, TemplateAddModelPkMixin, ListView):
    def get_queryset(self):
        model = get_object_or_404(models.CobraModel, pk=self.kwargs['model_pk'], owner=self.request.user)
        return model.rgefba_list.all()

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['form'] = forms.CobraRgeFbaForm()
        return context_data


class CobraRgeFbaDetailView(LoginRequiredMixin, TemplateAddModelPkMixin, DetailView):
    def get_object(self, queryset=None):
        self.model_object = get_object_or_404(models.CobraModel, pk=self.kwargs['model_pk'], owner=self.request.user)
        return get_object_or_404(self.model_object.rgefba_list.all(), pk=self.kwargs['pk'])


class CobraRgeFbaCreateView(LoginRequiredMixin, InsertModelForFormMixin, TemplateAddModelPkMixin, CreateView):
    http_method_names = ['post']
    template_name = 'cobra_wrapper/cobrargefba_list.html'
    model = models.CobraRgeFba
    form_class = forms.CobraRgeFbaForm

    def form_valid(self, form: Form):
        form.instance.model = self.model_object
        response = super().form_valid(form)
        result = app.send_task(
            'cobra_computation.tasks.cobra_fba',
            kwargs={
                'pk': self.object.pk,
                'model_sbml': self.model_object.sbml_content,

backend/cobra_wrapper/templates/cobra_wrapper/cobramodel_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ object }}{% endblock title %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-2">
                <div class="bar-left"
                     style="width: 3px; height: {{ change_line_len }}px; background-color:#20c997"></div>
                <div class="bar-btn-group col-1">
                    <button class="row btn btn-sm-circle text-hover-green slide" data-toggle="hover"
                            data-content="Created"></button>
                    {% for change in latest_changes %}
                        {# <button type="button" class="row btn btn-sm-circle text-hover-green slide" data-toggle="hover" data-content="{{ change }}"></button> #}
                        <form method="post"
                              action="{% url 'cobra_wrapper:cobramodel_change_restore' object.pk change.pk %}">
                            {% csrf_token %}
                            <input type="submit" class="row btn btn-sm-circle text-hover-green slide"
                                   data-toggle="hover" data-content="{{ change }}" value>
                        </form>
                    {% endfor %}
                </div>
                <script>
                    $(function () {
                        $('[data-toggle="hover"]').popover({trigger: 'hover'})
                    })
                </script>
                <div class="col-12">
                    <div class="row">
                        <div class="text ml-4 bar-text text-muted">
                            Created<br>
                            {{ object.created_time.date|date:"Y-m-d" }}<br>
                            {{ object.created_time.time|date:"H:i:s" }}<br>
                        </div>
                        {% for change in latest_changes %}
                            <div class="text ml-4 bar-text text-muted">
                                {{ change.get_type_name }}<br>
                                {{ change.created_time.date|date:"Y-m-d" }}<br>
                                {{ change.created_time.time|date:"H:i:s" }}<br>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-8">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-content-between">
                        <h5 style="padding-top: 5px;">Model: {{ object.name }}</h5>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#shareModal">
                            <i class="fa fa-share-alt "></i>
                        </button>
                        <!-- Modal -->
                        <div class="modal fade" id="shareModal" tabindex="-1" role="dialog"
                             aria-labelledby="exampleModalLabel"
                             aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Share</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body" id="share-modal-body">
                                        <form method="post" action="{% url 'share:create_share' %}" onsubmit="return false">

                                            <div class="form-group row">
                                                <div class="col-12">
                                                    <label>description</label>
                                                    <input type="number" name="model_id" value="{{ object.pk }}" hidden>
                                                    {% csrf_token %}
                                                    <input type="text" class="form-control" name="desc">
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary"
                                                                data-dismiss="modal">Close
                                                        </button>
                                                        <button type="button" class="btn btn-primary" id="share">Share
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Information</h5>
                        <div class="list-group">
                            <a href="{% url 'cobra_wrapper:cobramodel_map' object.pk %}" class="btn btn-info">Metabolic
                                Map</a>
                            {% for reaction in reactions %}
                                <li
                                        class="list-group-item list-group-item-action">{{ reaction.name }}[{{ reaction.cobra_id }}]
                                </li>
                            {% endfor %}
                        </div>
                        <br>
                        <div class="btn-group-fixed">
                            <div class="row">
                                <button class="col btn btn-outline-light btn-side-circle text-hover-green" type="button"
                                data-toggle="modal" data-target="#ModalEditForm">Edit
                                </button>
                            </div>
                            <div class="row">
                                    <button class="col btn btn-outline-light btn-side-circle text-hover-red" type="button"
                                    data-toggle="modal" data-target="#ModalDeleteForm">Delete
                            </button>
                            </div>
                            <div class="row">
                                    <a href="{% url 'cobra_wrapper:cobrafba_list' object.pk %}"
                                    class="col btn btn-outline-light btn-side-circle text-hover-green">
                                     FBA
                                 </a>
                            </div>
                            <div class="row">
                                    <a href="{% url 'cobra_wrapper:cobrargefba_list' object.pk %}"
                                    class="col btn btn-outline-light btn-side-circle text-hover-green">
                                     RFBA
                                 </a>
                            </div>
                            <div class="row">
                                    <a href="{% url 'cobra_wrapper:cobrafva_list' object.pk %}"
                                    class="col btn btn-outline-light btn-side-circle text-hover-green">
                                     FVA
                                 </a>
                            </div>
                        </div>
                        {% comment %}
                        <div class="row justify-content-around">
                            <button class="col-2 btn btn-outline-light btn-side-circle text-hover-green" type="button"
                                    data-toggle="modal" data-target="#ModalEditForm">Edit
                            </button>
                            <button class="col-2 btn btn-outline-light btn-side-circle text-hover-red" type="button"
                                    data-toggle="modal" data-target="#ModalDeleteForm">Delete
                            </button>
                            <a href="{% url 'cobra_wrapper:cobrafba_list' object.pk %}"
                               class="col-2 btn btn-outline-light btn-side-circle text-hover-green">
                                FBA
                            </a>
                            <a href="{% url 'cobra_wrapper:cobrargefba_list' object.pk %}"
                               class="col-2 btn btn-outline-light btn-side-circle text-hover-green">
                                RFBA
                            </a>
                            <a href="{% url 'cobra_wrapper:cobrafva_list' object.pk %}"
                               class="col-2 btn btn-outline-light btn-side-circle text-hover-green">
                                FVA
                            </a>
                        </div>
                        {% endcomment %}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <div class="list-group">
                    <li href="#" class="list-group-item list-group-item-action text-light"
                        style="background-color:#20c997">
                        Biobricks
                    </li>
                    {% for biobrick in biobricks %}
                        <a href="http://bio.biomaster-uestc.com/public/index.php/detail/{{ biobrick.part_name }}"
                           class="list-group-item list-group-item-action">{{ biobrick.part_name }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <br>
    </div>

    <div class="modal fade" id="ModalEditForm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Edit Model</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% for form in forms %}
                        <form method="post" action="{% url 'cobra_wrapper:cobramodel_update_form' object.pk %}">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input type="submit" class="btn btn-info col-2" value="Submit">
                        </form>
                        <hr>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="ModalDeleteForm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Confirm</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'cobra_wrapper:cobramodel_confirm_delete' object.id %}" method="post">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
                            <div class="col-sm-10">
                                <p>Are you sure to delete: {{ object }}?</p>
                            </div>
                        </div>
                        <div class="form-group row d-flex justify-content-center">
                            <input type="submit" class="btn btn-info col-2" value="Delete">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        var token = $('input[name="csrfmiddlewaretoken"]').attr('value');
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", token);
                }
            }
        });
        $('#share').on('click', function () {

            var token = $('input[name="csrfmiddlewaretoken"]').attr('value');
            $.ajax({
                url: '/share/create',
                method: 'post',
                data: {
                    "model_id": {{ object.pk }},
                    "desc" : $('input[name="desc"]').attr('value')
                },

                success: function (res) {
                    console.log(res);
                    $('#share-modal-body').html('Share successfully! Url: ' + res.url);
                },
                error: function (err) {
                    console.log('ajax err.')
                }
            })
        });
    </script>
{% endblock content %}

backend/cobra_wrapper/templates/cobra_wrapper/cobramodel_map.html
{% load static %}


<html lang="en">
<title>Model Analysis</title>
<!-- 新 Bootstrap4 核心 CSS 文件 -->
<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<script src="{% static "javascript/jquery.min.js" %}"></script>
<!-- popper.min.js 用于弹窗、提示、下拉菜单 -->
<script src="{% static "javascript/popper.min.js" %}"></script>
<!-- 最新的 Bootstrap4 核心 JavaScript 文件 -->
<script src="{% static "javascript/bootstrap.min.js" %}"></script>

<!-- Escher -->
<script src="{% static "javascript/escher.min.js" %}"></script>

<!-- LP Solver -->
<script src="{% static "javascript/glpk.min.js" %}"></script>

<!-- Knockout CSS -->
<link rel="stylesheet" href="{% static "css/knockout.css" %}"/>

<meta charset="utf-8"/>
<meta name="viewport"
      content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"/>

<body>
<div id="map_container"></div>
<div id="knockout-bottom">
    <div id="knockout-status"></div>
    <div id="knockout-buttons">
        <button id="reset-button" class="btn btn-info" style="margin-right:3em;">
            Reset
        </button>
    </div>
</div>
</body>

<!-- Code -->
<script src="{% static "javascript/knockout.js" %}"></script>

<script>
    let url = window.location.href;
    url = url.slice(0, url.length - 4);
    url += 'json';
    load_builder(function (builder) {
        load_model(model => {
            var old_model = escher.utils.clone(model);
            optimize_loop(builder, model);
            escher.libs.d3_select('#reset-button')
                .on('click', () => {
                    model = escher.utils.clone(old_model);
                    optimize_loop(builder, model);
                });
        }, url);
    });
</script>

</html>