backend/backend/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.staticfiles.views import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(template_name='index.html', extra_context={
        "ignore_header": True
    }, redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('accounts/', include('accounts.urls')),  # for user signup
    path('cobra/', include('cobra_wrapper.urls')),
    path('database/', include('bigg_database.urls')),
    path('data/', include('data_wrapper.urls')),
    path('share/', include('share.urls')),
    path('favicon.ico', serve, {'path': 'icon/favicon.ico'}),
]

backend/bigg_database/urls.py
from django.urls import path

from search.views import DatabaseSearchView
from . import views
from . import api_views

app_name = 'bigg_database'
urlpatterns = [
    path('search', DatabaseSearchView.as_view(),
         name='search'),
    path('model/<int:pk>', views.ModelDetailView.as_view(),
         name='model_detail'),
    path('reaction/<int:pk>', views.ReactionDetailView.as_view(),
         name='reaction_detail'),
    path('metabolite/<int:pk>', views.MetaboliteDetailView.as_view(),
         name='metabolite_detail'),
    path('gene/<int:pk>', views.GeneDetailView.as_view(),
         name='gene_detail'),
    path('model/<int:pk>/genes', views.GenesInModel.as_view(),
         name='genes_in_model'),
    path('model/<int:pk>/metabolites', views.MetabolitesInModel.as_view(),
         name='metabolites_in_model'),
    path('model/<int:pk>/reactions', views.ReactionsInModel.as_view(),
         name='reactions_in_model'),
    path('reaction/<int:pk>/metabolites', views.MetabolitesInReaction.as_view(),
         name='metabolites_in_reaction'),
    path('reaction/<int:pk>/genes', views.GenesInReaction.as_view(),
         name='genes_in_reaction'),
    path('gene/<int:pk>/models', views.GeneFromModels.as_view(),
         name='gene_from_models'),
    path('metabolite/<int:pk>/models', views.MetaboliteFromModels.as_view(),
         name='metabolite_from_models'),
    path('reaction/<int:pk>/models', views.ReactionFromModels.as_view(),
         name='reaction_from_models'),
    path('gene/<int:pk>/reactions', views.GeneFromReactions.as_view(),
         name='gene_from_reactions'),
    path('metabolite/<int:pk>/reactions', views.MetaboliteFromReactions.as_view(),
         name='metabolite_from_reactions'),
    path('model/<int:from_model_pk>/metabolites/<int:to_model_pk>',
         views.ModelMetaboliteRelationshipDetailView.as_view(),
         name='model_metabolite_relationship_detail'),
    path('model/<int:from_model_pk>/reactions/<int:to_model_pk>',
         views.ModelReactionRelationshipDetailView.as_view(),
         name='model_reaction_relationship_detail'),
    path('reaction/<int:from_model_pk>/metabolites/<int:to_model_pk>',
         views.ReactionMetaboliteRelationshipDetailView.as_view(),
         name='reaction_metabolite_relationship_detail'),
    path('reaction/<int:from_model_pk>/genes/<int:to_model_pk>',
         views.ReactionGeneRelationshipDetailView.as_view(),
         name='reaction_gene_relationship_detail'),
    path('model/<int:from_model_pk>/genes/<int:to_model_pk>',
         views.ModelGeneRelationshipDetailView.as_view(),
         name='model_gene_relationship_detail'),

    # ApiViews
    path('api/search/reaction', api_views.ReactionSearchApiView.as_view(),
         name='api_search_reaction'),
    path('api/search/metabolite', api_views.MetaboliteSearchApiView.as_view(),
         name='api_search_metabolite'),
    path('api/search/model', api_views.ModelSearchApiView.as_view(),
         name='api_search_model'),
    path('api/search/gene', api_views.GeneSearchApiView.as_view(),
         name='api_search_gene'),
    path('api/model/<int:pk>', api_views.ModelDetailApiView.as_view(),
         name='api_model_detail'),
    path('api/reaction/<int:pk>', api_views.ReactionDetailApiView.as_view(),
         name='api_reaction_detail'),
    path('api/metabolite/<int:pk>', api_views.MetaboliteDetailApiView.as_view(),
         name='api_metabolite_detail'),
    path('api/gene/<int:pk>', api_views.GeneDetailApiView.as_view(),
         name='api_gene_detail'),
    path('api/model/<int:pk>/genes', api_views.GenesInModel.as_view(),
         name='api_genes_in_model'),
    path('api/model/<int:pk>/metabolites', api_views.MetabolitesInModelApiView.as_view(),
         name='api_metabolites_in_model'),
    path('api/model/<int:pk>/reactions', api_views.ReactionsInModelApiView.as_view(),
         name='api_reactions_in_model'),
    path('api/reaction/<int:pk>/metabolites', api_views.MetabolitesInReactionApiView.as_view(),
         name='api_metabolites_in_reaction'),
    path('api/reaction/<int:pk>/genes', api_views.GenesInReactionApiView.as_view(),
         name='api_genes_in_reaction'),
    path('api/gene/<int:pk>/models', api_views.GeneFromModelsApiView.as_view(),
         name='api_gene_from_models'),
    path('api/metabolite/<int:pk>/models', api_views.MetaboliteFromModelsApiView.as_view(),
         name='api_metabolite_from_models'),
    path('api/reaction/<int:pk>/models', api_views.ReactionFromModelsApiView.as_view(),
         name='api_reaction_from_models'),
    path('api/gene/<int:pk>/reactions', api_views.GeneFromReactionsApiView.as_view(),
         name='api_gene_from_reactions'),
    path('api/metabolite/<int:pk>/reactions', api_views.MetaboliteFromReactionsApiView.as_view(),
         name='api_metabolite_from_reactions'),
]

backend/data_wrapper/urls.py
from django.urls import path

from . import views

app_name = 'data_wrapper'
urlpatterns = [
    path('add_models/', views.AddDataModelToCobra.as_view(), name='add_models'),
    path('add_reactions/', views.AddDataReactionToCobra.as_view(), name='add_reactions'),
    # path('add_metabolites/', views.AddDataMetaboliteToCobra.as_view(), name='add_metabolites'),
]

backend/share/urls.py
from django.urls import path

from . import views

app_name = 'share'
urlpatterns = [
    path('create/', views.CreateShareLinkView.as_view(), name='create_share'),
    path('model/<int:pk>', views.ModelShareView.as_view(), name='shared_cobra_model'),
    path('addToModel/', views.AddToMyModel.as_view(), name='add_to_model')
    # path('reaction/<int:pk>', views.ReactionShareView.as_view(), name='shared_cobra_reaction'),
    # path('metabolite/<int:pk>', views.MetaboliteShareView.as_view(), name='shared_cobra_metabolite'),
]

backend/bigg_database/models.py
from django.db import models as _models

from .fields import JSONField


class Model(_models.Model):
    bigg_id = _models.CharField(unique=True, max_length=127, db_index=True)

    COMPARTMENTS_CHOICES = (
        ('c', 'cytosol'),
        ('e', 'extracellular space'),
        ('p', 'periplasm'),
        ('m', 'mitochondria'),
        ('x', 'peroxisome/glyoxysome'),
        ('r', 'endoplasmic reticulum'),
        ('v', 'vacuole'),
        ('n', 'nucleus'),
        ('g', 'golgi apparatus'),
        ('u', 'thylakoid'),
        ('l', 'lysosome'),
        ('h', 'chloroplast'),
        ('f', 'flagellum'),
        ('s', 'eyespot'),
        ('im', 'intermembrane space of mitochondria'),
        ('cx', 'carboxyzome'),
        ('um', 'thylakoid membrane'),
        ('cm', 'cytosolic membrane'),
        ('i', 'i'))

    compartments = JSONField()
    version = _models.CharField(max_length=127)

    class Meta:
        verbose_name = 'Model'


class Reaction(_models.Model):
    bigg_id = _models.CharField(max_length=127, unique=True, db_index=True)
    name = _models.CharField(max_length=255, blank=True)
    models = _models.ManyToManyField(
        Model, through='ModelReaction', through_fields=('reaction', 'model'))

    reaction_string = _models.CharField(max_length=7000)
    pseudoreaction = _models.BooleanField()

    database_links = JSONField()

    class Meta:
        verbose_name = 'Reaction'


class Metabolite(_models.Model):
    bigg_id = _models.CharField(unique=True, max_length=127, db_index=True)
    name = _models.CharField(max_length=511)

    reactions = _models.ManyToManyField(
        Reaction, through='ReactionMetabolite', through_fields=('metabolite', 'reaction'))
    models = _models.ManyToManyField(
        Model, through='ModelMetabolite', through_fields=('metabolite', 'model'))

    formulae = JSONField(max_length=127)
    charges = _models.IntegerField(blank=True, null=True)

    database_links = JSONField()

    class Meta:
        verbose_name = 'Metabolite'


class Gene(_models.Model):
    bigg_id = _models.CharField(unique=True, max_length=127, db_index=True)
    name = _models.CharField(max_length=127)
    rightpos = _models.IntegerField()
    leftpos = _models.IntegerField()
    chromosome_ncbi_accession = _models.CharField(default='', max_length=127)
    mapped_to_genbank = _models.BooleanField()

    strand = _models.CharField(max_length=127)
    protein_sequence = _models.TextField()
    dna_sequence = _models.TextField()

    genome_name = _models.CharField(max_length=127)
    genome_ref_string = _models.CharField(max_length=127)

    database_links = JSONField()

    reactions = _models.ManyToManyField(
        Reaction, through='ReactionGene', through_fields=('gene', 'reaction'))
    models = _models.ManyToManyField(Model)

    class Meta:
        constraints = [
            _models.CheckConstraint(check=_models.Q(rightpos__gte=_models.F('leftpos')),
                                    name='right_gte_left')
        ]

        verbose_name = 'Gene'


class ReactionGene(_models.Model):
    gene_reaction_rule = _models.TextField()

    reaction = _models.ForeignKey(Reaction, on_delete=_models.CASCADE)
    gene = _models.ForeignKey(Gene, on_delete=_models.CASCADE)

    class Meta:
        unique_together = ('reaction', 'gene')


class ReactionMetabolite(_models.Model):
    stoichiometry = _models.IntegerField()

    reaction = _models.ForeignKey(Reaction, on_delete=_models.CASCADE)
    metabolite = _models.ForeignKey(Metabolite, on_delete=_models.CASCADE)

    class Meta:
        unique_together = ('reaction', 'metabolite')


class ModelMetabolite(_models.Model):
    organism = _models.CharField(max_length=127)

    model = _models.ForeignKey(Model, on_delete=_models.CASCADE)
    metabolite = _models.ForeignKey(Metabolite, on_delete=_models.CASCADE)

    class Meta:
        unique_together = ('model', 'metabolite')


class ModelReaction(_models.Model):
    organism = _models.CharField(max_length=127)

    lower_bound = _models.FloatField()
    upper_bound = _models.FloatField()

    subsystem = _models.CharField(max_length=127, blank=True, null=True)

    gene_reaction_rule = _models.TextField()

    model = _models.ForeignKey(Model, on_delete=_models.CASCADE)
    reaction = _models.ForeignKey(Reaction, on_delete=_models.CASCADE)

    class Meta:
        unique_together = ('model', 'reaction')
        constraints = [
            _models.CheckConstraint(check=_models.Q(upper_bound__gte=_models.F('lower_bound')),
                                    name='upper_gte_lower')
        ]

backend/search/models.py
from django.db import models

# Create your models here.

backend/search/forms.py
import heapq

from django import forms
from django.apps import apps
from fuzzywuzzy import fuzz
from haystack.forms import ModelSearchForm
from haystack.query import SQ
from bigg_database.models import Gene, Reaction


class ModifiedModelSearchForm(ModelSearchForm):
    q = forms.CharField(required=True, label='Search',
                        widget=forms.TextInput(attrs={'type': 'search'}))

    '''
    This should be an class, not str
    '''
    default_model = None

    def __init__(self, models, *args, **kwargs):
        """
        The first model in models will be the default model to search if default_model undefined
        """
        super().__init__(*args, **kwargs)

        '''
        Create model field, describes which model to search
        '''
        if not models:
            raise ValueError("Models to search must be specified")

        self.fields['model'] = forms.ChoiceField(required=False,
                                                 choices=[
                                                     (o._meta.label, o._meta.verbose_name)
                                                     for o in models
                                                 ])

        '''
        This will create something like
        ```
        ['bigg_database.Reaction',
        'bigg_database.Model',
        'bigg_database.Metabolite',
        'bigg_database.Gene']
        ```
        '''
        self.models = models
        self.models_str = [
            o._meta.label
            for o in models
        ]
        self.queryset = None

    @property
    def search_model(self):
        query_model = None
        if self.cleaned_data.get('model'):
            query_model = apps.get_model(self.cleaned_data.get('model'))

        return query_model or self.default_model or self.models[0]

    def search(self):
        if not self.is_valid():
            return self.no_query_found()

        self.queryset = self._search_model()
        return self.queryset

    def _search_model(self, model=None):
        keyword = self.cleaned_data['q']

        model = model or self.search_model

        return self.searchqueryset \
            .models(model) \
            .filter(SQ(content__fuzzy=keyword)) \
            .order_by('-_score')

    def additional_model_count(self):
        if not self.is_valid():
            total_number = {
                model._meta.verbose_name: 0
                for model in self.models
            }
        else:
            total_number = {
                model._meta.verbose_name: len(self._search_model(model))
                for model in self.models
                if model != self.search_model
            }

        if self.queryset is not None:
            this_cnt = len(self.queryset)
        else:
            this_cnt = len(self.search())

        total_number[self.search_model._meta.verbose_name] = this_cnt

        return total_number


class BiggOptimizedSearchForm(ModifiedModelSearchForm):
    Score_Threshold = 50

    def fuzzywuzzy_search(self, model):
        keyword = self.cleaned_data['q']
        data = []
        for ins in model.objects.all():
            score = fuzz.partial_ratio(ins.bigg_id, keyword)
            if hasattr(ins, 'name'):
                score_name = fuzz.partial_ratio(ins.name, keyword)
                score = max(score, score_name)
            if score >= self.Score_Threshold:
                heapq.heappush(data, (score, ins.id, ins))
        data_len = len(data)
        return [element[2] for element in reversed([heapq.heappop(data) for _ in range(data_len)])]

    def _search_model(self, model=None):
        model = model or self.search_model
        if model in [Gene, Reaction] or model != self.search_model:
            return super()._search_model(model)
        else:
            return self.fuzzywuzzy_search(model)

backend/search/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import FormView
from haystack.generic_views import SearchMixin

from bigg_database.models import Gene as BiggGene
from bigg_database.models import Metabolite as BiggMetabolite
from bigg_database.models import Model as BiggModel
from bigg_database.models import Reaction as BiggReaction

from .forms import ModifiedModelSearchForm, BiggOptimizedSearchForm


class BaseSearchView(SearchMixin, FormView):
    form_class = ModifiedModelSearchForm
    models = None

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(self.models, **self.get_form_kwargs())

    def get(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.queryset = form.search()
        context = {
            self.form_name: form,
            'query': form.cleaned_data['q'],
            'object_list': self.queryset,
            'search_model': form.search_model._meta.verbose_name,
            'search_result_count': len(self.queryset)
        }
        return context


class DatabaseSearchView(BaseSearchView):
    form_class = BiggOptimizedSearchForm
    models = [BiggModel, BiggReaction, BiggMetabolite, BiggGene]
    template_name = 'bigg_database/search_result.html'
    paginate_by = 10

    def form_valid(self, form):
        context = super().form_valid(form)

        total_number = form.additional_model_count()
        context = {
            'total_count': sum(count for _, count in total_number.items()),
            'counts': total_number,
            **context
        }
        context = self.get_context_data(**context)
        return self.render_to_response(context)

    def form_invalid(self, form):
        return redirect(reverse('accounts:profile'))

backend/bigg_database/templates/bigg_database/db_links.html
<ul>
{% for db, links in db_links.items %}
    <li>
        {{ db }}:
        <ul>
        {% for link in links %}
            <li>
                <a href="{{ link.link }}">{{ link.id }}</a>
            </li>
        {% endfor %}
        </ul>
    </li>
{% endfor %}
</ul>

backend/bigg_database/templates/bigg_database/gene_list.html
<table class="table table-hover table-bordered mt-3">
    <thead>
        <tr>
            <th>BiGG ID</th>
            <th>Name</th>
            <th>Chromosome</th>
        </tr>
    </thead>
    <tbody>
    {% for gene in list %}
        <tr>
            <th><a href="{{ gene.detail_url }}">{{ gene.bigg_id }}</a></th>
            <th>{{ gene.name }}</th>
            <th>{{ gene.chromosome_ncbi_accession }}</th>
        </tr>
    {% endfor %}
    </tbody>
</table>

backend/bigg_database/templates/bigg_database/item_base.html
{% extends 'base.html' %}
{% block page_style %}
table.table tr td:first-child {font-weight: 600;}
{% endblock %}

backend/bigg_database/templates/bigg_database/list.html
{% if model == 'model' %}
{% include 'bigg_database/model_list.html' with list=list %}
{% elif model == 'reaction' %}
{% include 'bigg_database/reaction_list.html' with list=list %}
{% elif model == 'metabolite' %}
{% include 'bigg_database/metabolite_list.html' with list=list %}
{% elif model == 'gene' %}
{% include 'bigg_database/gene_list.html' with list=list %}
{% endif %}

backend/bigg_database/templates/bigg_database/metabolite_detail.html
{% extends 'bigg_database/item_base.html' %}
{% load render_list_tag %}
{% load favorite_tag %}
{% load static %}

{% block title %}
Metabolite: {{ meta.bigg_id }}
{% endblock %}

{% block content %}
    <div id="content" class="container mt-4">
        <div class="w-100 d-flex justify-content-between">
            <h4>{{ meta.name }} Metabolite</h4>
            {% if user.is_authenticated %}
                <a href="#" data-toggle="modal" data-target="#exampleModal">
					<h5>{% favorite_button meta %}</h5>
				</a>
            {% endif %}
        </div>
        <table class="table table-hover table-bordered mt-3">
            <tbody>
            <tr>
                <td>BIGG ID</td>
                <td>{{ meta.bigg_id }}</td>
            </tr>
            <tr>
                <td>Descriptive Name</td>
                <td>{{ meta.name }}</td>
            </tr>
            <tr>
                <td>Formulae</td>
                <td>{{ meta.formulae|join:', ' }}</td>
            </tr>
            {% if meta.charges %}
            <tr>
                <td>Charges</td>
                <td>{{ meta.charges }}</td>
            </tr>
            {% endif %}
            {% if meta.database_links %}
                <tr>
                    <td>External Database Links</td>
                    <td>
                        {% include 'bigg_database/db_links.html' with db_links=meta.database_links only %}
                    </td>
                </tr>
            {% endif %}
            <tr>
                <td><a href="{% url 'bigg_database:metabolite_from_reactions' meta.id %}">
                    Reactions Containing {{ gene.bigg_id }}</a></td>
                <td>
                    {% render_list_tag meta.reactions.all 'reaction' 'reaction_metabolite_relationship_detail' id=meta.id reverse=True %}
                </td>
            </tr>
            <tr>
                <td><a href="{% url 'bigg_database:metabolites_in_model' meta.id %}">
                    Models Containing {{ gene.bigg_id }}</a></td>
                <td>
                    {% render_list_tag meta.models.all 'model' 'model_metabolite_relationship_detail' id=meta.id reverse=True %}
                </td>
            </tr>
            </tbody>
        </table>
    </div>
<script src="{% static "javascript/favorite_button.js" %}"></script>
{% endblock %}

backend/bigg_database/templates/bigg_database/model_detail.html
{% extends 'bigg_database/item_base.html' %}
{% load render_list_tag %}
{% load favorite_tag %}
{% load static %}

{% block title %}
    Model: {{ model.bigg_id }}
{% endblock %}

{% block content %}
    <div id="content" class="container mt-4">
        <div class="w-100 d-flex justify-content-between">
            <h4>Model {{ model.bigg_id }} contains</h4>
            {% if user.is_authenticated %}
                <a href="#" data-toggle="model" data-target="#exampleModal">
                    <h5>{% favorite_button model %}</h5>
                </a>
            {% endif %}
        </div>
        <table class="table table-hover table-bordered mt-3">
            <thead>
            <tr>
                <th>Component</th>
                <th>Count</th>
            </tr>
            </thead>
            <tbody>
            <!-- Row clickable or count clickable? -->
            <tr>
                <td>Reactions</td>
                <td><a href="{% url 'bigg_database:reactions_in_model' model.id %}">{{ model.reaction_set.count }}</a>
                </td>
            </tr>
            <tr>
                <td>Metabolites</td>
                <td>
                    <a href="{% url 'bigg_database:metabolites_in_model' model.id %}">{{ model.metabolite_set.count }}</a>
                </td>
            </tr>
            <tr>
                <td>Genes</td>
                <td><a href="{% url 'bigg_database:genes_in_model' model.id %}">{{ model.gene_set.count }}</a></td>
            </tr>
            </tbody>
        </table>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-outline-light text-hover-green" data-toggle="modal"
                data-target="#ModalCenter">
            add to computation
        </button>
        <!-- Modal -->
        <div class="modal fade" id="ModalCenter" tabindex="-1" role="dialog" aria-labelledby="ModalCenterTitle"
             aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="ModalCenterTitle">Model</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form id="addModelForm" method="post" action="{% url 'data_wrapper:add_models' %}">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <input type="text" name="name" class="form-control">
                                <input type="text" name="desc" class="form-control">
                                <input type="hidden" name="model_bigg_id" value="{{ model.bigg_id }}"
                                       class="form-control">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-outline-light text-hover-green" form="addModelForm">Add
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static "javascript/favorite_button.js" %}"></script>


{% endblock %}

backend/bigg_database/templates/bigg_database/reaction_detail.html
{% extends 'bigg_database/item_base.html' %}
{% load render_list_tag %}
{% load favorite_tag %}
{% load static %}

{% block title %}
    Reaction: {{ reaction.bigg_id }}
{% endblock %}

{% block content %}
    <div id="content" class="container mt-4">
        <div class="w-100 d-flex justify-content-between">
            <h4>{{ reaction.name }} Reaction</h4>
            {% if user.is_authenticated %}
                <a href="#" data-toggle="modal" data-target="#exampleModal">
                    <h5>{% favorite_button reaction %}</h5>
                </a>
            {% endif %}
        </div>
        <table class="table table-hover table-bordered mt-3">
            <tbody>
            <tr>
                <td>BIGG ID</td>
                <td>{{ reaction.bigg_id }}</td>
            </tr>
            <tr>
                <td>Descriptive Name</td>
                <td>{{ reaction.name }}</td>
            </tr>
            <tr>
                <td>Reaction</td>
                <td>{{ reaction.reaction_string|safe }}</td>
            </tr>
            <tr>
                <td>Is pseudoreaction?</td>
                <td>
                  {% if reaction.pseudoreaction %}
                  √
                  {% else %}
                  X
                  {% endif %}
                </td>
            </tr>
            {% if reaction.database_links %}
                <tr>
                    <td>External Database Links</td>
                    <td>
                        {% include 'bigg_database/db_links.html' with db_links=reaction.database_links only %}
                    </td>
                </tr>
            {% endif %}
            <tr>
                <td><a href="{% url 'bigg_database:metabolites_in_reaction' reaction.id %}">
                    Related Metabolites</a></td>
                <td>
                    <p>{% render_list_tag reaction.metabolite_set.all 'metabolite' 'reaction_metabolite_relationship_detail' id=reaction.id %}</p>
                </td>
            </tr>
            <tr>
                <td><a href="{% url 'bigg_database:reaction_from_models' reaction.id %}">
                    Models Containing {{ reaction.bigg_id }}</a></td>
                <td>
                    {% render_list_tag reaction.models.all 'model' 'model_reaction_relationship_detail' id=reaction.id reverse=True %}
                </td>
            </tr>
            </tbody>
        </table>
        <form method="post" action="{% url 'data_wrapper:add_reactions' %}">
          {% csrf_token %}
          <div class="input-group mb-3">
            <select class="form-control">
                {% for user_model in user_models %}
                <option value="{{ user_model.id }}">{{ user_model.name }}</option>
                {% endfor %}
            </select>
            <input type="hidden" name="reaction_pk" value="{{ reaction.id }}">
            <div class="input-group-append">
              <button class="btn btn-outline-light text-hover-green" type="submit" id="submit-button">add to your model</button>
            </div>
          </div>
        </form>
    </div>

    <script src="{% static "javascript/favorite_button.js" %}"></script>
{% endblock %}

backend/bigg_database/templates/bigg_database/relationship_lookup_list.html
{% extends "bigg_database/item_base.html" %}
{% load bigg_database_tags %}
{% load render_list_tag %}
{% block title %}
Relationship lookup for {{ from_model_name }}
{% endblock %}

{% block content %}
    <div id="content" class="container mt-4">
        <h2>The {{ to_model_name }}s in {{ from_model.bigg_id }}</h2>

        {% if to_model_name == 'metabolite' %}
            {% if from_model_name == 'model' %}
                {% render_list_tag result_list 'metabolite' 'model_metabolite_relationship_detail' id=from_model.id contain_organism=True %}
            {% elif from_model_name == 'reaction' %}
                {% render_list_tag result_list 'metabolite' 'reaction_metabolite_relationship_detail' id=from_model.id contain_stoichiometry=True %}
            {% endif %}
        {% elif to_model_name == 'reaction' %}
            {% render_list_tag result_list 'reaction' 'model_reaction_relationship_detail' id=from_model.id contain_organism=True %}
        {% elif to_model_name == 'gene' %}
            {% if from_model_name == 'model' %}
                {% render_list_tag result_list 'gene' 'model_gene_relationship_detail' id=from_model.id %}
            {% elif from_model_name == 'reaction' %}
                {% render_list_tag result_list 'gene' 'reaction_gene_relationship_detail' id=from_model.id %}
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

backend/bigg_database/templates/bigg_database/search.html
{% extends "base.html" %}

{% block title %}
    Search
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <h2>Search</h2>

        <form method="get" action="{% url 'bigg_database:search' %}">
            <p>
                <label for="id_q">Search:</label>
                <input id="id_q" type="search" name="q" required>
            </p>
            <input type="submit" value="Search">
        </form>
    </div>
{% endblock %}