backend/accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.UserSignUp.as_view(), name='signup'),
    path('signup/done', TemplateView.as_view(template_name="accounts/signup_done.html"), name="signup_done"),
    path('activate/<str:uidb64>/<str:token>', views.UserActivation.as_view(), name='activate'),
    path('profile/', views.UserProfile.as_view(), name='profile'),
    # path('guide/', TemplateView.as_view(template_name="accounts/guide_book.html"), name="guide"),
    path('pack/', views.UserPack.as_view(), name='pack')
]

backend/backend/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.staticfiles.views import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(template_name='index.html', extra_context={
        "ignore_header": True
    }, redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('accounts/', include('accounts.urls')),  # for user signup
    path('cobra/', include('cobra_wrapper.urls')),
    path('database/', include('bigg_database.urls')),
    path('data/', include('data_wrapper.urls')),
    path('share/', include('share.urls')),
    path('favicon.ico', serve, {'path': 'icon/favicon.ico'}),
]

backend/bigg_database/urls.py
from django.urls import path

from search.views import DatabaseSearchView
from . import views
from . import api_views

app_name = 'bigg_database'
urlpatterns = [
    path('search', DatabaseSearchView.as_view(),
         name='search'),
    path('model/<int:pk>', views.ModelDetailView.as_view(),
         name='model_detail'),
    path('reaction/<int:pk>', views.ReactionDetailView.as_view(),
         name='reaction_detail'),
    path('metabolite/<int:pk>', views.MetaboliteDetailView.as_view(),
         name='metabolite_detail'),
    path('gene/<int:pk>', views.GeneDetailView.as_view(),
         name='gene_detail'),
    path('model/<int:pk>/genes', views.GenesInModel.as_view(),
         name='genes_in_model'),
    path('model/<int:pk>/metabolites', views.MetabolitesInModel.as_view(),
         name='metabolites_in_model'),
    path('model/<int:pk>/reactions', views.ReactionsInModel.as_view(),
         name='reactions_in_model'),
    path('reaction/<int:pk>/metabolites', views.MetabolitesInReaction.as_view(),
         name='metabolites_in_reaction'),
    path('reaction/<int:pk>/genes', views.GenesInReaction.as_view(),
         name='genes_in_reaction'),
    path('gene/<int:pk>/models', views.GeneFromModels.as_view(),
         name='gene_from_models'),
    path('metabolite/<int:pk>/models', views.MetaboliteFromModels.as_view(),
         name='metabolite_from_models'),
    path('reaction/<int:pk>/models', views.ReactionFromModels.as_view(),
         name='reaction_from_models'),
    path('gene/<int:pk>/reactions', views.GeneFromReactions.as_view(),
         name='gene_from_reactions'),
    path('metabolite/<int:pk>/reactions', views.MetaboliteFromReactions.as_view(),
         name='metabolite_from_reactions'),
    path('model/<int:from_model_pk>/metabolites/<int:to_model_pk>',
         views.ModelMetaboliteRelationshipDetailView.as_view(),
         name='model_metabolite_relationship_detail'),
    path('model/<int:from_model_pk>/reactions/<int:to_model_pk>',
         views.ModelReactionRelationshipDetailView.as_view(),
         name='model_reaction_relationship_detail'),
    path('reaction/<int:from_model_pk>/metabolites/<int:to_model_pk>',
         views.ReactionMetaboliteRelationshipDetailView.as_view(),
         name='reaction_metabolite_relationship_detail'),
    path('reaction/<int:from_model_pk>/genes/<int:to_model_pk>',
         views.ReactionGeneRelationshipDetailView.as_view(),
         name='reaction_gene_relationship_detail'),
    path('model/<int:from_model_pk>/genes/<int:to_model_pk>',
         views.ModelGeneRelationshipDetailView.as_view(),
         name='model_gene_relationship_detail'),

    # ApiViews
    path('api/search/reaction', api_views.ReactionSearchApiView.as_view(),
         name='api_search_reaction'),
    path('api/search/metabolite', api_views.MetaboliteSearchApiView.as_view(),
         name='api_search_metabolite'),
    path('api/search/model', api_views.ModelSearchApiView.as_view(),
         name='api_search_model'),
    path('api/search/gene', api_views.GeneSearchApiView.as_view(),
         name='api_search_gene'),
    path('api/model/<int:pk>', api_views.ModelDetailApiView.as_view(),
         name='api_model_detail'),
    path('api/reaction/<int:pk>', api_views.ReactionDetailApiView.as_view(),
         name='api_reaction_detail'),
    path('api/metabolite/<int:pk>', api_views.MetaboliteDetailApiView.as_view(),
         name='api_metabolite_detail'),
    path('api/gene/<int:pk>', api_views.GeneDetailApiView.as_view(),
         name='api_gene_detail'),
    path('api/model/<int:pk>/genes', api_views.GenesInModel.as_view(),
         name='api_genes_in_model'),
    path('api/model/<int:pk>/metabolites', api_views.MetabolitesInModelApiView.as_view(),
         name='api_metabolites_in_model'),
    path('api/model/<int:pk>/reactions', api_views.ReactionsInModelApiView.as_view(),
         name='api_reactions_in_model'),
    path('api/reaction/<int:pk>/metabolites', api_views.MetabolitesInReactionApiView.as_view(),
         name='api_metabolites_in_reaction'),
    path('api/reaction/<int:pk>/genes', api_views.GenesInReactionApiView.as_view(),
         name='api_genes_in_reaction'),
    path('api/gene/<int:pk>/models', api_views.GeneFromModelsApiView.as_view(),
         name='api_gene_from_models'),
    path('api/metabolite/<int:pk>/models', api_views.MetaboliteFromModelsApiView.as_view(),
         name='api_metabolite_from_models'),
    path('api/reaction/<int:pk>/models', api_views.ReactionFromModelsApiView.as_view(),
         name='api_reaction_from_models'),
    path('api/gene/<int:pk>/reactions', api_views.GeneFromReactionsApiView.as_view(),
         name='api_gene_from_reactions'),
    path('api/metabolite/<int:pk>/reactions', api_views.MetaboliteFromReactionsApiView.as_view(),
         name='api_metabolite_from_reactions'),
]

backend/cobra_wrapper/urls.py
from django.urls import path

from . import views, api_views

app_name = 'cobra_wrapper'
urlpatterns = [
    path('models/', views.CobraModelListView.as_view(), name='cobramodel_list'),
    path('models/<int:pk>/', views.CobraModelDetailView.as_view(), name='cobramodel_detail'),
    path('models/<int:pk>/map/', views.CobraModelMapView.as_view(), name='cobramodel_map'),
    path('models/<int:pk>/json/', api_views.CobraModelDetailJsonView.as_view(), name='cobramodel_detail_json'),
    path('models/create/', views.CobraModelCreateView.as_view(), name='cobramodel_create_form'),
    path('models/<int:pk>/delete/', views.CobraModelDeleteView.as_view(), name='cobramodel_confirm_delete'),
    path('models/<int:pk>/update/', views.CobraModelUpdateView.as_view(), name='cobramodel_update_form'),
    path('models/<int:pk>/change/<int:change_pk>/restore/', views.CobraModelChangeRestoreView.as_view(),
         name='cobramodel_change_restore'),

    path('models/<int:model_pk>/fba/', views.CobraFbaListView.as_view(), name='cobrafba_list'),
    path('models/<int:model_pk>/fba/<int:pk>/', views.CobraFbaDetailView.as_view(), name='cobrafba_detail'),
    path('models/<int:model_pk>/fba/<int:pk>/json/', api_views.CobraFbaDetailJsonView.as_view(),
         name='cobrafba_detail_json'),
    path('models/<int:model_pk>/fba/create/', views.CobraFbaCreateView.as_view(), name='cobrafba_create_form'),
    path('models/<int:model_pk>/fba/<int:pk>/delete/', views.CobraFbaDeleteView.as_view(),
         name='cobrafba_confirm_delete'),

    path('models/<int:model_pk>/rgefba/', views.CobraRgeFbaListView.as_view(), name='cobrargefba_list'),
    path('models/<int:model_pk>/rgefba/<int:pk>/', views.CobraRgeFbaDetailView.as_view(), name='cobrargefba_detail'),
    path('models/<int:model_pk>/rgefba/<int:pk>/json/', api_views.CobraRgeFbaDetailJsonView.as_view(),
         name='cobrargefba_detail_json'),
    path('models/<int:model_pk>/rgefba/create/', views.CobraRgeFbaCreateView.as_view(), name='cobrargefba_create_form'),
    path('models/<int:model_pk>/rgefba/<int:pk>/delete/', views.CobraRgeFbaDeleteView.as_view(),
         name='cobrargefba_confirm_delete'),

    path('models/<int:model_pk>/fva/', views.CobraFvaListView.as_view(), name='cobrafva_list'),
    path('models/<int:model_pk>/fva/<int:pk>/', views.CobraFvaDetailView.as_view(), name='cobrafva_detail'),
    path('models/<int:model_pk>/fva/<int:pk>/json', api_views.CobraFvaDetailJsonView.as_view(),
         name='cobrafva_detail_json'),
    path('models/<int:model_pk>/fva/create/', views.CobraFvaCreateView.as_view(), name='cobrafva_create_form'),
    path('models/<int:model_pk>/fva/<int:pk>/delete/', views.CobraFvaDeleteView.as_view(),
         name='cobrafva_confirm_delete'),
]

backend/share/urls.py
from django.urls import path

from . import views

app_name = 'share'
urlpatterns = [
    path('create/', views.CreateShareLinkView.as_view(), name='create_share'),
    path('model/<int:pk>', views.ModelShareView.as_view(), name='shared_cobra_model'),
    path('addToModel/', views.AddToMyModel.as_view(), name='add_to_model')
    # path('reaction/<int:pk>', views.ReactionShareView.as_view(), name='shared_cobra_reaction'),
    # path('metabolite/<int:pk>', views.MetaboliteShareView.as_view(), name='shared_cobra_metabolite'),
]

backend/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Foresyn - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">

    <script src="{% static "javascript/jquery.min.js" %}"></script>

    <script src="{% static "javascript/popper.min.js" %}"></script>

    <script src="{% static "javascript/bootstrap.min.js" %}"></script>

    <link rel="stylesheet" href="https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css">

    <link rel="stylesheet" href="{% static "css/mycss.css" %}">

    <link rel="apple-touch-icon" sizes="57x57" href="{% static "icon/apple-icon-57x57.png" %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static "icon/apple-icon-60x60.png" %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static "icon/apple-icon-72x72.png" %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static "icon/apple-icon-76x76.png" %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static "icon/apple-icon-114x114.png" %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static "icon/apple-icon-120x120.png" %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static "icon/apple-icon-144x144.png" %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static "icon/apple-icon-152x152.png" %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "icon/apple-icon-180x180.png" %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static "icon/android-icon-192x192.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "icon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static "icon/favicon-96x96.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "icon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "icon/manifest.json" %}">
    <link rel="shortcut icon" href="{% static 'icon/favicon.ico' %}"/>
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static "icon/ms-icon-144x144.png" %}">
    <meta name="theme-color" content="#ffffff">

    <style>
        {% block page_style %}
        {% endblock %}
    </style>
    {% block page_css %}{% endblock %}
</head>

<body>
    {% if not ignore_header %}
    {% include "header.html" %}
    {% endif %}
    {#    <div id="content">#}
    {% block content %}{% endblock %}
    {#    </div>#}
    {% if not ignore_header %}
    <br><br>
    {% endif %}
    {% include "footer.html" %}
</body>

</html>

backend/templates/footer.html
{#{% load static %}#}
{#<footer class="mt-4">#}
{#    <link rel="stylesheet" href="{% static "/css/footer.css" %}">#}
{#    <section class="footer text-center bg-primary text-light d-flex align-items-center justify-content-center">#}
{#        <h4>Created By USTC-Software, 2019</h4>#}
{#    </section>#}
{#</footer>#}
{##}
{#<style>#}
    {#footer section {background-color: #105ae4; color: #eee; text-align: center;height: 300px;}#}
{#</style>#}

backend/templates/header.html
{% load static %}

<header>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-md navbar-dark" style="background-color: #20c997">
    <div class="container">
      <!-- Brand -->
      <span class="navbar-brand">
          <a href="/">
        <img src="{% static "image/logo.png" %}" style="height:30px">
          </a>
      </span>
      <form class="form-inline" action="{% url "bigg_database:search" %}">
        <input class="form-control form-control-sm mr-sm-2 form-circle" type="search" placeholder="  Search" aria-label="Search" name="q" value="{% if request.GET.q %}{{ request.GET.q }}{% endif %}">
      </form>

      <!-- Toggler/collapsibe Button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Navbar links -->
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="nav navbar-nav">
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == "profile" %}active{% endif %}" href="{% url 'accounts:profile' %}">My Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if 'cobra' in request.resolver_match.url_name %}active{% endif %}" href="{% url 'cobra_wrapper:cobramodel_list' %}">My Models</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://2019.igem.org/Team:USTC-Software/Demonstrate">Guide Book</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == "pack" %}active{% endif %}" href="{% url 'accounts:pack' %}">My Pack</a>
          </li>
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item nav-link text-black text-center" data-toggle="tab" href="#dropdown1">dropdown1</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item nav-link text-black text-center" data-toggle="tab" href="#dropdown2">dropdown2</a>
            </div>
          </li>  -->
        </ul>
        <div class="ml-auto">
          <span class="navbar-brand">
              {% if user.is_authenticated %}
            <img class="rounded" src="{% static "image/avatar.jpg" %}" style="height:30px">
            <a class="btn btn-outline-light btn-sm text-hover-green" href="{% url 'logout' %}">Logout</a>
              {% else %}
              <a class="btn btn-outline-light btn-sm text-hover-green" href="{% url 'login' %}">Login</a>
              {% endif %}
          </span>
        </div>
      </div>
    </div>
  </nav>
</header>

backend/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    Index
{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/animate.min.css" %}">
    <link rel="stylesheet" href="{% static "css/mycss.css" %}">
    <script src="{% static "javascript/jquery.min.js" %}"></script>
    <script src="{% static "javascript/bootstrap.min.js" %}"></script>
    <div style="position: fixed;height: 100%;width: 100%;background: #f1fafe;"></div>
    <div class="d-flex justify-content-center align-items-center"
         style="position: absolute;height: 100%;width: 100%;background: url(/static/image/background.jpg);background-size: contain;background-position:center;">
        <div class="card"
             style=" width: 24rem;height: 250px;border-radius: 20px;position: relative;bottom: 0px;display:none;z-index:1">
            <div class="card-body" style="padding-top: 70px;">
                <form action="{% url 'login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" name="username" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" name="password" placeholder="Password">
                    </div>
                    <input type="hidden" name="next" value="{{ next }}">
                    <input type="submit" class="btn btn-outline-light btn-side-circle text-hover-green"
                           style="width: 100%;" value="Login">

                    <div>
                <span><a href="{% url 'accounts:signup' %}">Don't have an account?</a></span>
                <span class="float-right"><a href="{% url 'password_reset' %}">Lost password?</a></span>
            </div>
                </form>

            </div>
        </div>
    </div>
    <div class="d-flex justify-content-center align-items-center" style="position: absolute;height: 100%;width: 100%;">
        <img src="{% static "image/hand.png" %}" style="width: 24rem; position: relative;top:170px">
    </div>
    <div class="d-flex justify-content-center align-items-center" style="position: absolute;height: 100%;width: 100%;">
        <img src="{% static "image/gene.png" %}" class="animated infinite bounce slow gene" style="width: 12rem; position: relative;bottom:-50px;
    z-index:2;animation: jump-gene 1s;animation-iteration-count: infinite;animation-direction: alternate;cursor:pointer;">
    </div>
    <script>
        $('img.gene').click(function () {
            $(this).removeClass('animated infinite bounce slow')
            $(this).css('animation', 'move-gene 1s')
            $(this).css('bottom', '150px')
            $('div.card').addClass('animated fadeInUp')
            $('div.card').css('display', 'inline')
        });
    </script>

{% endblock %}